typography_spectrum: 0.5487758711894218
color:
  brandColors:
    - '#ffffff'
    - '#d8002a'
    - '#ff0000'
    - '#aa0000'
    - '#800000'
  brandStrength: 0.07945647838894315
  lightness: 0.35426535651613356
  saturation: 0.1682027442236938
  rhythmicContrast: 0.46164367722365823
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2907998585069349
analytics:
  google: UA-32992476-3
  facebook: null
  twitter: null
author:
  name: Ferrix Hovi
name: Ironman 2018
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Projekti
    id: 6c2d5e9e-563a-40da-8265-49e1a64c6332
    type: content
  - name: Projekti
    id: 246e9d3a-e839-42ea-a21c-7dd76d1fa6d2
    type: content
favicon: null
title: IM18
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/2c125cd6c23a6de0012d8b24ffe1c0ffba91a871.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/2c125cd6c23a6de0012d8b24ffe1c0ffba91a871.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Treeniä yhden pienen päätöksen perässä
purpose: []
